---
all:
  children:
    openwebui:
      hosts:
        photon:
          ansible_connection: local
          ansible_host: 10.0.105.14
          ansible_user: root
          keycloak_url: "https://auth.{{ lookup('ansible.builtin.env', 'DOMAIN') | default('localhost', true) }}"

