---
all:
  children:
    openwebui:
      hosts:
        openwebui-01:
          ansible_host: "{{ lookup('env', 'OPENWEBUI_HOST') }}"
          ansible_user: "{{ lookup('env', 'OPENWEBUI_SSH_USER') | default('ansible', true) }}"
