apiVersion: 1

contactPoints:
  - orgId: 1
    name: Discord
    receivers:
      - name: Discord Webhook
        type: discord
        settings:
          url: ${GRAFANA_DISCORD_WEBHOOK_URL}
          use_discord_title: true
          message: |
            {{ .CommonLabels.alertname }}
            {{ range .Alerts }}
            **Status:** {{ .Status }}
            **Summary:** {{ .Annotations.summary }}
            **Description:** {{ .Annotations.description }}
            {{ end }}
